### ISSUE TITLE
Backport of traverseXxx functions

### ISSUE THREAD

**Issue by dnowak** [cashapp/quiver#49]
Hi,

Are you going to backport the `traverseXxx` (like `traverseEither`) methods from Arrow?

I was upgrading my project to Arrow 1.2.0 and assumed that all useful stuff deprecated in Arrow will be moved to Quiver, but such functions are missing.

BR,
Darek

**Comment by millyrowboat** [comment]
@dnowak Hi there!

Yes that is the plan 👍 We plan to add in the next couple of weeks, but if you have a pressing need, feel free to open a PR with the methods added 😄

**Comment by dnowak** [comment]
Hi @millyrowboat,

I'm not in a rush :-). I may work on a PR if I find time.
